+check if remote is configured

diff --git a/publish b/publish
--- a/publish
+++ b/publish
@@ -14,6 +14,12 @@ then
 	exit 0
 fi
 
+if ! ( git remote get-url origin 2>/dev/null | grep -qE "github\.com|gitlab\.com" >/dev/null )
+then
+	echo "Error: Repo not linked to Github.com or Gitlab.com"
+	exit 1
+fi
+
 ## Parse arguments
 
 if test "x$1" = "x" || test "x$1" = "xpatch"
