publish: +run npm test

diff --git a/publish b/publish
--- a/publish
+++ b/publish
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+SCRIPTPATH="$(readlink -f 2>/dev/null || perl -MCwd -e 'print Cwd::abs_path shift' $0)"
+SCRIPTDIR="$(dirname "${SCRIPTPATH}")"
+
+
 ## Test if there are uncommited changes
 
 if test "x$(git status --porcelain=v1 2>/dev/null)" != "x"
@@ -18,6 +22,19 @@ if ! ( git remote get-url origin 2>/dev/null | grep -qE "github\.com|gitlab\.com
 then
 	echo "Error: Repo not linked to Github.com or Gitlab.com"
 	exit 1
+fi
+
+## Run npm test
+
+TESTSCRIPT="$("${SCRIPTDIR}/get-json" --file "package.json" --key "scripts.test")"
+if test "x${TESTSCRIPT}" != "x" && test "x${TESTSCRIPT}" != 'xecho "Error: no test specified" && exit 1'
+then
+	echo "Run npm test"
+	if ! npm test
+	then
+		echo "Error: npm test not successful." >&2
+		exit 1
+	fi
 fi
 
 ## Parse arguments
